openapi: 3.1.1
info:
  title: Seller API V1
  description: Seller API
  version: '1.0'
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-KEY
security:
- ApiKeyAuth: []
servers:
- url: https://sellerapi.ggchest.com
paths:
  /v1/games:
    $ref: ../openapi/dictionary/games/games.json
  /v1/games/{id}/{offerType}/attributes:
    $ref: ../openapi/offer-attribute/offer-attributes.json
  /v1/games/{id}/currency:
    $ref: ../openapi/dictionary/games-currencies/currency-by-game.json
  /v1/offers:
    $ref: ../openapi/sellers/offers/offers.json
  /v1/offers/accounts:
    $ref: ../openapi/sellers/offers/offers-accounts.json
  /v1/offers/currency:
    $ref: ../openapi/sellers/offers/offers-currency.json
  /v1/offers/items:
    $ref: ../openapi/sellers/offers/offers-items.json
  /v1/offers/{id}:
    $ref: ../openapi/sellers/offers/offers-id.json
  /v1/offers/accounts/{id}:
    $ref: ../openapi/sellers/offers/offers-accounts-id.json
  /v1/offers/items/{id}:
    $ref: ../openapi/sellers/offers/offers-items-id.json
  /v1/offers/currency/{id}:
    $ref: ../openapi/sellers/offers/offers-currency-id.json
  /v1/offers/{id}/toggle:
    $ref: ../openapi/sellers/offers/offers-toggle.json
  /v1/offers/{id}/price:
    $ref: ../openapi/sellers/offers/update-offer-price.json
  /v1/offers/{id}/icon:
    $ref: ../openapi/sellers/offers/attach-icon.json
  /v1/offers/{offerId}/icon/{iconId}:
    $ref: ../openapi/sellers/offers/delete-offer-icon.json

